version: "3.7"
services:
  vrc-status-bot:
    image: node:11.6.0
    environment:
      TOKEN: BOT_TOKEN
      VRC_USERNAME: USERNAME
      VRC_PASSWORD: PASSWORD
      GUILD_ID: GUILD
      CHANNEL_ID: CHANNEL
      SETTING_CHANNEL_ID: CHANNEL
      CYCLE: 60
    volumes:
      - .:/app
      - ./db:/db
    working_dir: /app
    entrypoint: bash -c "yarn && yarn build && yarn start"
